import 'package:latlong2/latlong.dart';
import '../models/models.dart';

class MockData {
  static final List<Category> categories = [
    const Category(
      id: '1',
      name: 'Raw Materials',
      type: ListingCategory.rawMaterials,
      icon: 'assets/icons/sand.svg',
    ),
    const Category(
      id: '2',
      name: 'Trucks & Haulage',
      type: ListingCategory.trucksHaulage,
      icon: 'assets/icons/truck.svg',
    ),
    const Category(
      id: '3',
      name: 'Moving Services',
      type: ListingCategory.movingServices,
      icon: 'assets/icons/moving.svg',
    ),
    const Category(
      id: '4',
      name: 'Furniture Stores',
      type: ListingCategory.furnitureStores,
      icon: 'assets/icons/furniture.svg',
    ),
    const Category(
      id: '5',
      name: 'Equipment Rental',
      type: ListingCategory.equipmentRental,
      icon: 'assets/icons/crane.svg',
    ),
  ];

  static final List<Supplier> suppliers = [
    Supplier(
      id: 's1',
      name: 'Lekki Sand & Gravel Ltd',
      phone: '08012345678',
      email: 'contact@lekkisand.com',
      isVerified: true,
      location: 'Lekki Phase 1, Lagos',
      coordinates: const LatLng(6.4589, 3.6015),
      rating: 4.8,
      listingsCount: 15,
      viewsCount: 1200,
      contactsCount: 450,
      joinedDate: 'Jan 2023',
      status: 'Active',
      avatar: 'https://i.pravatar.cc/150?u=s1',
    ),
    Supplier(
      id: 's2',
      name: 'Ikeja Haulage Solutions',
      phone: '08087654321',
      email: 'info@ikejahaulage.com',
      isVerified: false,
      location: 'Ikeja, Lagos',
      coordinates: const LatLng(6.6018, 3.3515),
      rating: 4.2,
      listingsCount: 8,
      viewsCount: 850,
      contactsCount: 120,
      joinedDate: 'Mar 2023',
      status: 'Active',
      avatar: 'https://i.pravatar.cc/150?u=s2',
    ),
    Supplier(
      id: 's3',
      name: 'Swift Movers Surulere',
      phone: '09011223344',
      email: 'hello@swiftmovers.ng',
      isVerified: true,
      location: 'Surulere, Lagos',
      coordinates: const LatLng(6.4952, 3.3541),
      rating: 4.9,
      listingsCount: 5,
      viewsCount: 2100,
      contactsCount: 890,
      joinedDate: 'Nov 2022',
      status: 'Active',
      avatar: 'https://i.pravatar.cc/150?u=s3',
    ),
  ];

  static final List<Listing> listings = [
    Listing(
      id: 'l1',
      title: 'Sharp Sand (20 Tons)',
      description: 'High quality sharp sand for construction. Delivery available within Lagos.',
      price: 85000,
      unit: 'Trip',
      category: ListingCategory.rawMaterials,
      supplierId: 's1',
      supplierName: 'Lekki Sand & Gravel Ltd',
      isSupplierVerified: true,
      location: 'Lekki, Lagos',
      coordinates: const LatLng(6.4589, 3.6015),
      distance: 2.5,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      views: 150,
      contacts: 45,
      images: const [
        'https://images.unsplash.com/photo-1533044309907-0fa3413da946?w=500',
      ],
    ),
    Listing(
      id: 'l2',
      title: 'Flatbed Truck for Hire',
      description: 'Strong flatbed truck for long distance haulage. Well maintained.',
      price: 120000,
      unit: 'Day',
      category: ListingCategory.trucksHaulage,
      supplierId: 's2',
      supplierName: 'Ikeja Haulage Solutions',
      isSupplierVerified: false,
      location: 'Ikeja, Lagos',
      coordinates: const LatLng(6.6018, 3.3515),
      distance: 12.0,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      views: 85,
      contacts: 12,
      images: const [
        'https://images.unsplash.com/photo-1586191582151-f73972d10727?w=500',
      ],
    ),
    Listing(
      id: 'l3',
      title: '3-Bedroom Apartment Move',
      description: 'Professional moving service including packing and offloading.',
      price: 65000,
      unit: 'Service',
      category: ListingCategory.movingServices,
      supplierId: 's3',
      supplierName: 'Swift Movers Surulere',
      isSupplierVerified: true,
      location: 'Surulere, Lagos',
      coordinates: const LatLng(6.4952, 3.3541),
      distance: 8.5,
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      views: 320,
      contacts: 110,
      images: const [
        'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=500',
      ],
    ),
    Listing(
      id: 'l4',
      title: 'Granite (Stone Dust)',
      description: 'Fine granite stone dust for block making and paving.',
      price: 95000,
      unit: 'Trip',
      category: ListingCategory.rawMaterials,
      supplierId: 's1',
      supplierName: 'Lekki Sand & Gravel Ltd',
      isSupplierVerified: true,
      location: 'Ajah, Lagos',
      coordinates: const LatLng(6.4523, 3.6121),
      distance: 5.0,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      views: 98,
      contacts: 20,
      images: const [
        'https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?w=500',
      ],
    ),
  ];
}
